package com.example.dependencyagent.worker;

import com.example.dependencyagent.domain.AnalysisJob;
import com.example.dependencyagent.domain.FixJob;
import java.time.Instant;
import org.springframework.stereotype.Component;

@Component
public class MockWorkerClient implements WorkerClient {

    @Override
    public WorkerAnalysisResult analyze(AnalysisJob job) {
        String summary = "Mock analysis completed for " + job.getRepository().getOriginalFilename()
                + ". Maven dependency upgrade candidates will be produced by the Python worker later.";
        String reportJson = """
                {
                  "jobId": "%s",
                  "repositoryName": "%s",
                  "buildTool": "maven",
                  "generatedAt": "%s",
                  "findings": [
                    {
                      "dependencyId": "org.springframework.boot:spring-boot-starter-web",
                      "groupId": "org.springframework.boot",
                      "artifactId": "spring-boot-starter-web",
                      "currentVersion": "managed",
                      "recommendedVersion": "managed-by-parent",
                      "latestVersion": "managed-by-parent",
                      "scope": "compile",
                      "usageLocation": "pom.xml",
                      "priority": "medium",
                      "category": "version_bump",
                      "reason": "Mock finding. Real worker will inspect dependency trees, migration guides, and build output.",
                      "migrationGuideRefs": [],
                      "fixAvailable": true
                    }
                  ],
                  "summary": {
                    "totalDependencies": 1,
                    "upgradeCandidates": 1,
                    "criticalCount": 0,
                    "highCount": 0,
                    "mediumCount": 1,
                    "lowCount": 0
                  }
                }
                """.formatted(job.getId(), job.getRepository().getName(), Instant.now()).strip();
        String payload = """
                {"mock":true,"phase":"analysis","findings":[]}
                """.strip();
        return new WorkerAnalysisResult(summary, reportJson, payload);
    }

    @Override
    public WorkerFixResult fix(FixJob job) {
        String plan = "Mock fix plan created for " + job.getFixBy()
                + " selection.";
        String patch = "No patch generated by mock worker.";
        String payload = """
                {"mock":true,"phase":"fix","fixBy":"%s","dependencyIds":"%s","category":"%s","patches":[]}
                """.formatted(
                job.getFixBy(),
                job.getDependencyIds(),
                job.getCategory()
        ).strip();
        String testOutput = "Mock test run passed. Real worker will run the detected build verification command.";
        String rebuiltReportJson = """
                {"mock":true,"phase":"rebuilt_report","fixedDependencyIds":"%s","remainingFindings":[]}
                """.formatted(job.getDependencyIds()).strip();
        return new WorkerFixResult(plan, patch, testOutput, rebuiltReportJson, payload);
    }
}
